name: oceanstream
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - jinja2
  - netcdf4
  - numpy
  - pytz
  - scipy
  - pandas
  - requests
  - geopy
  - dask
  - dask-image
  - pynmea2
  - xarray
  - zarr
  - fsspec
  - psutil>=5.9.1
  - more-itertools==8.13.0
  - pydantic>2
  - haversine
  - matplotlib
  - pip
  - git
  - pip:
      - git+https://github.com/OceanStreamIO/echopype-dev.git@oceanstream
